on:
  push:
    branches:
      - main

env: 
  GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

name: Render my CV

jobs:
  render:
    name: Render my CV
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-tinytex@v2
      - name: Install dependencies
        run: |
          install.packages("rmarkdown")
          install.packages("magrittr")
          install.packages("usethis")
          install.packages("pagedown")
          install.packages("googlesheets4")
          install.packages("glue")
          install.packages("dplyr")
          install.packages("tidyr")		  
          install.packages("devtools")
          install.packages("fs")
          devtools::install_github("nstrayer/datadrivencv")
        shell: Rscript {0}
      - name: Render my document to PDF
        run: Rscript -e 'rmarkdown::render("cv.Rmd", output_format = "pdf_document")'
      - name: Commit results
        run: |
          git add cv*
          git commit -m 'Re-build CV' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
